from flask import Flask, render_template, jsonify
import json
import os

app = Flask(__name__)

# Base directory for VEX reports generated by the batch processor
REPORTS_DIR = "reports/batch"

@app.route('/')
def index():
    return render_template('dashboard.html')

@app.route('/api/results')
def get_results():
    all_results = []
    if not os.path.exists(REPORTS_DIR):
        return jsonify([])
        
    for filename in os.listdir(REPORTS_DIR):
        if filename.startswith("vex_") and filename.endswith(".json"):
            with open(os.path.join(REPORTS_DIR, filename), 'r') as f:
                try:
                    data = json.load(f)
                    # Flatten for the UI
                    for vuln in data.get('vulnerabilities', []):
                        for threat in vuln.get('threats', []):
                            all_results.append({
                                "cve": vuln.get('cve'),
                                "details": threat.get('details'),
                                "assets": threat.get('product_ids'),
                                "timestamp": data.get('document', {}).get('tracking', {}).get('initial_release_date')
                            })
                except:
                    continue
    return jsonify(all_results)

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=9001)
